version: "3.9"
services:
    backend:
        image: recetario
        container_name: recetario
        build: .
        ports:
            - 8080:8080
        networks:
            - api
networks:
    api: